version: '3.2'

services:
  postgres:
    image: postgres:14.5
    container_name: alethea-db-container
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_DB: 'doemgjhiuy687'
      POSTGRES_USER: 'uLkdhFGFev'
      POSTGRES_PASSWORD: 'Fgh.-23_4gj+SJ,o'
    volumes:
      - .db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: vendori-redis
    image: redis:5.0.7-alpine
    volumes:
      - .redis-data:/data
    ports:
      - "6379:6379"
